[package]
name = "jsume-typst"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Moozon Wei <muzhenweizh@gmail.com>"]
license = "MIT"
description = "A simple typst resume template for jsume"
homepage = "https://github.com/jsume/jsume-typst"
repository = "https://github.com/jsume/jsume-typst"
keywords = ["cv", "resume", "JSON resume"]
categories = ["cv"]
exclude = [
  ".github",
  "docs",
  "scripts",
  "tests",
  ".typstignore",
  "Justfile",
  "thumbnail.png",
]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
